name: Webpage

on:
  push:
    branches:
      - main
    paths:
      - "install.cfg"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  webpage:
    runs-on: ubuntu-latest
    name: Compile Webpage
    steps:
      - uses: actions/checkout@v4
      - name: Compile Webpage
        uses: instructions-d-installation/web-installation-instruction-action@v0.1.0
      - name: Deploy Webpage
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./public
          